version: 2
updates:
  - package-ecosystem: "pip"
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: "America/Chicago"
    reviewers:
      - "1898andCo/portal-code-owners"
