---
name: Check Manifest
on: # yamllint disable-line rule:truthy
  push:

permissions: read-all

jobs:
  check_manifest:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install check-manifest

      - name: Run check-manifest
        run: check-manifest > check-manifest-report.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Check Manifest Report
          path: check-manifest-report.txt
