---
name: Ruff Lint

on: # yamllint disable-line rule:truthy
  push:

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      repository-projects: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{secrets.PAT || secrets.GITHUB_TOKEN}}
          fetch-depth: 0 # If you use VALIDATE_ALL_CODEBASE = true, you can remove this line to improve performances

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: sudo apt-get install postgresql libpq-dev

      - name: Install Module
        run: pip install .[dev]

      - name: Run Ruff Linter
        run: ruff check . > ruff-report.txt

      - name: Upload Artifact
        if: ${{success() || failure()}}
        uses: actions/upload-artifact@v4
        with:
          name: ruff-report
          path: ruff-report.txt
